#version: '3.8'      # Docker compose version -> after 3.8 version, Don't need to write
services:
  db:     # Define the mariadb service container -> this container name is used at server:environment
    image: mariadb:11.6     # mariadb version
    container_name: mariadb     # container name
    ports:
      - "${DB_PORT}:${DB_PORT}"     # Map port 3306 on the host to port 3306 in the container
    environment:      # Set environment variables for the mariadb container
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}      # Password for the root user
      - MYSQL_DATABASE=${DB_NAME}      # Name of the created database
    volumes:
      - db-data:/var/lib/mysql      # Persist database data in the docker volume

  server:     # Define the server container
    env_file:
      - .env      # Load a environment file
    build:      # Configuration to build the docker image for the web application service
      context: .     # Path to the directory containing DockerFile
      dockerfile: Dockerfile      # Name of the Dockerfile
      platforms:
        - linux/amd64
    ports:
      - "${APP_PORT}:${APP_PORT}"     # Map port 8080 on the host to port 8080 in the container
    environment:      # Set environment variables for the server container
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:${DB_PORT}/${DB_NAME}     # Database connection URL; "db" refers to the db service name
      - SPRING_DATASOURCE_USERNAME=${DB_USER}     # Username for the database connection
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}     # Password for the database connection
    depends_on:
      - db      # Ensure the server container starts before this service container

volumes:
  db-data: